### ISSUE TITLE
`Export selected text as...` doesn't work if anything before current command is selected

### ISSUE THREAD

**Issue by Enteleform** [neil-orans/hyper-savetext#4]
When anything before the current command is selected, the `Export selected text as...` option remains disabled.

```
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>this_is_the_current_command
```

For example, if `this_is_the_current_command` or any part of that text is selected, the option is enabled. If the selection includes anything before or including the `C` of `C:\>`, the option is disabled. So in this case, `:\>this_is_the_current_command` would be the largest possible selection that works with the selected text function.

**Comment by neil-orans** [comment]
[I can't seem to replicate this issue either.](https://i.imgur.com/QAJzefd.gif) What other plugins are you using, if any?

**Comment by Enteleform** [comment]
```yaml
"dependencies": {
  "hyper-tabs-enhanced": "latest",
  "hypercwd":            "latest",
  "hyper-statusline":    "latest",
  "hyperlayout":         "latest",
  "hyper-savetext":      "latest",
  "hyper-pane":          "latest"
}
```

Okay, I just tested selecting completely before `C:\>` and that does work. Did you try selecting both before & after the cwd? That's where I run into the issue:

![](https://user-images.githubusercontent.com/10906415/39730204-44fd328a-522e-11e8-84bf-1bca50e3725d.gif)
